
const ESTADOS = {
  'TJAC': true,
  'TJAL': true,
  'TJAM': true,
  'TJAP': false,
  'TJBA': true,
  'TJCE': true,
  'TJDFT': true,
  'TJES': false,
  'TJGO': false,
  'TJMA': true,
  'TJMG': true,
  'TJMS': true,
  'TJMT': false,
  'TJPA': false,
  'TJPB': false,
  'TJPE': false,
  'TJPI': false,
  'TJPR': false,
  'TJRJ': false,
  'TJRN': true,
  'TJRO': false,
  'TJRR': false,
  'TJRS': false,
  'TJSC': true,
  'TJSE': false,
  'TJSP': true,
  'TJTO': false,
}

module.exports = { ESTADOS };